import Header from '@/components/header';
import PageGuard from '@/features/auth/ui/page-guard';
import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Trading Jutsu',
  description: 'Generated by create next app',
};

/**
 * Applies the stored theme before the browser paints, so a dark-mode user never
 * sees a flash of the light theme. `useTheme` (see `components/theme-switch`)
 * only applies it in an effect, which runs after first paint.
 *
 * Runs as a parser-blocking inline script — the Metadata API cannot express
 * this, and `next/script`'s `beforeInteractive` still resolves too late. On a
 * first visit it seeds the key from the OS preference so the switch has an
 * explicit value to read.
 */
const applyStoredTheme = `
(function () {
  try {
    var key = 'heroui-theme';
    var stored = localStorage.getItem(key);
    var theme =
      stored ||
      (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
    if (!stored) localStorage.setItem(key, theme);
    document.documentElement.classList.add(theme);
    document.documentElement.setAttribute('data-theme', theme);
  } catch (e) {}
})();
`;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      // The script below adds the theme class before React hydrates.
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <script dangerouslySetInnerHTML={{ __html: applyStoredTheme }} />
        <SessionProvider>
          <PageGuard>
            <Header />
            <div className="p-4">{children}</div>
          </PageGuard>
        </SessionProvider>
      </body>
    </html>
  );
}
